-- Project Verdant V1 schema (PRD §9.1, §9.2)
-- All timestamps are timestamptz generated by the database.
-- Randomness uses the core gen_random_uuid() (pg_catalog), not pgcrypto.

-- ---------------------------------------------------------------------------
-- profiles: public game identity and progression summary
-- ---------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username_canonical text not null unique check (username_canonical = lower(username_canonical)),
  username_display text not null,
  balance integer not null default 100 check (balance >= 0),
  lifetime_earned bigint not null default 0 check (lifetime_earned >= 0),
  balance_updated_at timestamptz not null default now(),
  tutorial_complete boolean not null default false,
  is_ranked boolean not null default true,
  created_at timestamptz not null default now()
);

create index profiles_balance_leaderboard_idx
  on public.profiles (balance desc, balance_updated_at asc);

-- ---------------------------------------------------------------------------
-- plots: one persistent 8x8 plot per account
-- ---------------------------------------------------------------------------
create table public.plots (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null unique references public.profiles(id) on delete cascade,
  grid_size integer not null default 8 check (grid_size = 8),
  version bigint not null default 1 check (version >= 1),
  updated_at timestamptz not null default now()
);

create index plots_owner_idx on public.plots (owner_id);

-- ---------------------------------------------------------------------------
-- plot_tiles: 64 authoritative tile records per plot
-- state: 0=untilled 1=tilled 2=watered 3=planted/growing 4=harvestable
-- mutation: 0=normal 1=gold 2=giant 3=rainbow
-- ---------------------------------------------------------------------------
create table public.plot_tiles (
  plot_id uuid not null references public.plots(id) on delete cascade,
  tile_index integer not null check (tile_index between 0 and 63),
  state smallint not null default 0 check (state between 0 and 4),
  crop_id text,
  planted_at timestamptz,
  ready_at timestamptz,
  mutation smallint not null default 0 check (mutation between 0 and 3),
  version bigint not null default 1 check (version >= 1),
  constraint plot_tiles_pk primary key (plot_id, tile_index)
);

create index plot_tiles_plot_idx on public.plot_tiles (plot_id);

-- ---------------------------------------------------------------------------
-- inventory_items: seed and harvested produce quantities
-- item_kind: 'seed' | 'produce'
-- ---------------------------------------------------------------------------
create table public.inventory_items (
  owner_id uuid not null references public.profiles(id) on delete cascade,
  item_kind text not null check (item_kind in ('seed', 'produce')),
  item_id text not null,
  mutation smallint not null default 0 check (mutation between 0 and 3),
  quantity integer not null default 0 check (quantity >= 0),
  constraint inventory_items_pk primary key (owner_id, item_kind, item_id, mutation)
);

create index inventory_owner_idx on public.inventory_items (owner_id);

-- ---------------------------------------------------------------------------
-- player_tools: permanent independent tool levels
-- ---------------------------------------------------------------------------
create table public.player_tools (
  owner_id uuid not null references public.profiles(id) on delete cascade,
  tool_id text not null check (tool_id in ('trowel', 'watering_can', 'seed_bag', 'scythe')),
  level smallint not null default 1 check (level between 1 and 3),
  updated_at timestamptz not null default now(),
  constraint player_tools_pk primary key (owner_id, tool_id)
);

-- ---------------------------------------------------------------------------
-- crop_catalog: server-authoritative crop tuning
-- ---------------------------------------------------------------------------
create table public.crop_catalog (
  crop_id text primary key,
  seed_cost integer not null check (seed_cost >= 0),
  growth_seconds integer not null check (growth_seconds > 0),
  yield_amount integer not null check (yield_amount > 0),
  base_sale integer not null check (base_sale >= 0),
  unlock_lifetime integer not null default 0 check (unlock_lifetime >= 0),
  catalog_version integer not null default 1,
  enabled boolean not null default true
);

-- ---------------------------------------------------------------------------
-- tool_catalog: server-authoritative tool upgrade tuning
-- area: 1=single tile, 2=three-tile line, 3=3x3 square
-- ---------------------------------------------------------------------------
create table public.tool_catalog (
  tool_id text not null check (tool_id in ('trowel', 'watering_can', 'seed_bag', 'scythe')),
  level smallint not null check (level between 1 and 3),
  cost integer not null check (cost >= 0),
  area smallint not null check (area between 1 and 3),
  cooldown_ms integer not null check (cooldown_ms > 0),
  catalog_version integer not null default 1,
  constraint tool_catalog_pk primary key (tool_id, level)
);

-- ---------------------------------------------------------------------------
-- game_rooms: room allocation state
-- ---------------------------------------------------------------------------
create table public.game_rooms (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'open' check (status in ('open', 'closed')),
  capacity smallint not null default 4 check (capacity = 4),
  created_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now()
);

create index game_rooms_status_idx on public.game_rooms (status, last_activity_at);

-- ---------------------------------------------------------------------------
-- room_members: atomic room membership and slot leases
-- ---------------------------------------------------------------------------
create table public.room_members (
  room_id uuid not null references public.game_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  slot smallint not null check (slot between 0 and 3),
  lease_expires_at timestamptz not null,
  reclaim_until timestamptz,
  joined_at timestamptz not null default now(),
  constraint room_members_pk primary key (room_id, user_id)
);

create unique index room_members_slot_uniq on public.room_members (room_id, slot);
-- One row per user, always: rows are deleted on leave/expire/rejoin, so a plain
-- unique index enforces "at most one live lease per user" without a non-immutable
-- partial predicate (Postgres rejects `where lease_expires_at > now()`).
create unique index room_members_user_uniq on public.room_members (user_id);

create index room_members_live_leases_idx on public.room_members (lease_expires_at);

-- ---------------------------------------------------------------------------
-- world_state: singleton authoritative global weather
-- weather: 0=sun 1=rain 2=heatwave 3=blood_moon
-- ---------------------------------------------------------------------------
create table public.world_state (
  singleton_id boolean primary key default true check (singleton_id),
  weather smallint not null default 0 check (weather between 0 and 3),
  epoch bigint not null default 1,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null default now() + interval '5 minutes',
  previous_weather smallint check (previous_weather between 0 and 3)
);

insert into public.world_state (singleton_id) values (true) on conflict do nothing;

-- ---------------------------------------------------------------------------
-- economy_transactions: immutable audit ledger
-- ---------------------------------------------------------------------------
create table public.economy_transactions (
  id bigint generated always as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null,
  amount integer not null,
  balance_after integer not null check (balance_after >= 0),
  idempotency_key uuid not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index economy_tx_owner_key_uniq on public.economy_transactions (owner_id, idempotency_key);
create index economy_tx_owner_time_idx on public.economy_transactions (owner_id, created_at desc);

-- ---------------------------------------------------------------------------
-- farm_operations: retry-safe farm operation record
-- ---------------------------------------------------------------------------
create table public.farm_operations (
  id bigint generated always as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  plot_id uuid not null references public.plots(id) on delete cascade,
  kind text not null,
  idempotency_key uuid not null,
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index farm_ops_owner_key_uniq on public.farm_operations (owner_id, idempotency_key);
create index farm_ops_owner_time_idx on public.farm_operations (owner_id, created_at desc);

-- ---------------------------------------------------------------------------
-- blocked_usernames: reserved and moderated username patterns
-- ---------------------------------------------------------------------------
create table public.blocked_usernames (
  normalized_term text primary key,
  reason text not null
);
